Rod Ciombor <br>
5/16/26<br>
CIS-2532-NET01<br>
Dr. Sheikh Shamsuddin<br>
Final Lab<br>

In [30]:
import sqlite3
import pandas as pd

connection = sqlite3.connect('books.db')
pd.options.display.max_columns = 10

<b><u>Exercise 17.1 a</u></b>
<br>
<b>Select all authors' last names from the authors table in descending order.</b>

In [9]:
pd.read_sql('SELECT last FROM authors ORDER BY last DESC', connection, index_col=['last'])

Empty DataFrame
Columns: []
Index: [Wald, Quirk, Deitel, Deitel, Deitel]

<b><u>Exercise 17.1 b</u></b>
<br>
<b>Select all book titles from the titles table in ascending order.</b>

In [11]:
pd.read_sql('SELECT title FROM titles ORDER BY title', connection, index_col=['title'])

Empty DataFrame
Columns: []
Index: [Android 6 for Programmers, Android How to Program, C How to Program, C++ How to Program, Internet & WWW How to Program, Intro to Python for CS and DS, Java How to Program, Visual Basic 2012 How to Program, Visual C# How to Program, Visual C++ How to Program]

<b><u>Exercise 17.1 c</u></b>
<br>
<b>Use an INNER JOIN to select all the books for a specific author. Include the title, copyright year and ISBN. Order the information alphabetically by title.</b>

In [22]:
print()
print('Titles by Harvey Deitel:')
print()
pd.read_sql('SELECT t.title, t.copyright, t.isbn FROM titles t INNER JOIN author_ISBN ai ON t.isbn = ai.isbn WHERE ai.id = 2 ORDER BY t.title', 
    connection, 
    index_col=['title']
)

Titles by Harvey Deitel:

                                 copyright        isbn
title
Android 6 for Programmers             2016  0134289366
Android How to Program                2017  0134444302
C How to Program                      2016  0133976890
C++ How to Program                    2017  0134448235
Internet & WWW How to Program         2012  0132151006
Intro to Python for CS and DS         2020  0135404673
Java How to Program                   2018  0134743350
Visual Basic 2012 How to Program      2014  0133406954
Visual C# How to Program              2017  0134601548
Visual C++ How to Program             2008  0136151574

<b><u>Exercise 17.1 d</u></b>
<br>
<b>Insert a new author into the authors table.</b>

In [26]:
cursor = connection.cursor()
cursor = cursor.execute("""INSERT INTO authors (first, last) VALUES ('Bob', 'Smith')""")
pd.read_sql('SELECT * FROM authors', connection, index_col=['id'])

        first    last
id
1        Paul  Deitel
2      Harvey  Deitel
3       Abbey  Deitel
4         Dan   Quirk
5   Alexander    Wald
6         Bob   Smith

<b><u>Exercise 17.1 e</u></b>
<br>
<b>Insert a new title for an author. Remember that the book must have an entry in the author_ISBN table and an entry in the titles table.</b>

In [28]:
new_isbn = '0131234567'
author_id = 6
titles_values = (new_isbn, 'The Art of Coding', 1, '2026')
author_isbn_values = (author_id, new_isbn)

cursor = connection.cursor()
cursor = cursor.execute(
    'INSERT INTO titles (isbn, title, edition, copyright) VALUES (?, ?, ?, ?)',
    titles_values
)
cursor = cursor.execute(
    'INSERT INTO author_ISBN (id, isbn) VALUES (?, ?)',
    author_isbn_values
)

pd.read_sql('SELECT t.title, t.edition, t.copyright, t.isbn FROM titles t INNER JOIN author_ISBN ai ON t.isbn = ai.isbn WHERE ai.id =? ORDER BY t.title', 
    connection,
    params = [author_id],
    index_col=['title']
)

                   edition copyright        isbn
title
The Art of Coding        1      2026  0131234567

<b><u>Exercise 17.2</u></b>
<br>
<b>Use the description attribute and fetchall() method from the cursor object</b>

In [29]:
cursor = connection.cursor()
cursor = cursor.execute('SELECT * FROM titles')
print('description contents')
print(cursor.description)
print()
print('fetchall() contents')
cursor.fetchall()

description contents
(('isbn', None, None, None, None, None, None), ('title', None, None, None, None, None, None), ('edition', None, None, None, None, None, None), ('copyright', None, None, None, None, None, None))

fetchall() contents

[('0135404673', 'Intro to Python for CS and DS', 1, '2020'),
 ('0132151006', 'Internet & WWW How to Program', 5, '2012'),
 ('0134743350', 'Java How to Program', 11, '2018'),
 ('0133976890', 'C How to Program', 8, '2016'),
 ('0133406954', 'Visual Basic 2012 How to Program', 6, '2014'),
 ('0134601548', 'Visual C# How to Program', 6, '2017'),
 ('0136151574', 'Visual C++ How to Program', 2, '2008'),
 ('0134448235', 'C++ How to Program', 10, '2017'),
 ('0134444302', 'Android How to Program', 3, '2017'),
 ('0134289366', 'Android 6 for Programmers', 3, '2016'),
 ('0131234567', 'The Art of Coding', 1, '2026')]